import { describe, it, expect } from 'vitest';
import { generateMigrationSQL } from '../../../src/transformer/transforms/kv-to-d1/schema-generator.js';

describe('schema-generator', () => {
  it('generates kv_store table for basic ops (get, set, del)', () => {
    const sql = generateMigrationSQL(['get', 'set', 'del']);
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS kv_store');
    expect(sql).toContain('key TEXT PRIMARY KEY');
    expect(sql).toContain('value TEXT NOT NULL');
    expect(sql).toContain('expires_at REAL');
  });

  it('generates kv_list table when operations include lpush', () => {
    const sql = generateMigrationSQL(['get', 'set', 'lpush', 'lrange']);
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS kv_list');
  });

  it('generates kv_list table when operations include lrange', () => {
    const sql = generateMigrationSQL(['lrange']);
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS kv_list');
  });

  it('omits kv_list table when no list operations present', () => {
    const sql = generateMigrationSQL(['get', 'set', 'del']);
    expect(sql).not.toContain('kv_list');
  });

  it('generates idx_kv_store_expires index always', () => {
    const sql = generateMigrationSQL(['get', 'set']);
    expect(sql).toContain('CREATE INDEX IF NOT EXISTS idx_kv_store_expires');
    expect(sql).toContain('expires_at');
  });

  it('generates idx_kv_list_key_position index only when kv_list is created', () => {
    const sqlWithList = generateMigrationSQL(['lpush']);
    expect(sqlWithList).toContain('CREATE INDEX IF NOT EXISTS idx_kv_list_key_position');

    const sqlNoList = generateMigrationSQL(['get', 'set']);
    expect(sqlNoList).not.toContain('idx_kv_list_key_position');
  });

  it('SQL uses CREATE TABLE IF NOT EXISTS (idempotent)', () => {
    const sql = generateMigrationSQL(['get', 'set', 'lpush']);
    // All CREATE TABLE statements should be IF NOT EXISTS
    const tableMatches = sql.match(/CREATE TABLE/g) || [];
    const ifNotExistsMatches = sql.match(/CREATE TABLE IF NOT EXISTS/g) || [];
    expect(tableMatches.length).toBe(ifNotExistsMatches.length);
  });

  it('SQL uses CREATE INDEX IF NOT EXISTS (idempotent)', () => {
    const sql = generateMigrationSQL(['get', 'set', 'lpush']);
    const indexMatches = sql.match(/CREATE INDEX/g) || [];
    const ifNotExistsMatches = sql.match(/CREATE INDEX IF NOT EXISTS/g) || [];
    expect(indexMatches.length).toBe(ifNotExistsMatches.length);
  });

  it('includes header comment with migration name', () => {
    const sql = generateMigrationSQL(['get']);
    expect(sql).toContain('-- Migration: 0001_kv_schema.sql');
    expect(sql).toContain('-- Generated by v2cf');
  });

  it('adapts to detected ops -- empty operations still generates kv_store', () => {
    const sql = generateMigrationSQL([]);
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS kv_store');
    expect(sql).not.toContain('kv_list');
  });
});
