export interface WebhookWorkerConfig {
  accountId: string;
  workerName: string;
}

/**
 * Generate the full source code for a Cloudflare Worker that receives
 * Vercel deployment webhooks, verifies the HMAC-SHA1 signature, and
 * triggers a rebuild via GitHub repository_dispatch.
 */
export function generateWebhookWorkerSource(config: WebhookWorkerConfig): string {
  return `// Auto-generated by v2cf -- Vercel webhook receiver Worker
// Worker: v2cf-sync-${config.workerName}

interface Env {
  VERCEL_WEBHOOK_SECRET: string;
  CLOUDFLARE_API_TOKEN: string;
  GITHUB_TOKEN: string;
  GITHUB_REPO: string; // "owner/repo"
}

// Basic deduplication: skip if same deploymentId processed within 60 seconds
const recentDeployments = new Map<string, number>();

async function verifySignature(
  rawBody: string,
  signature: string | null,
  secret: string
): Promise<boolean> {
  if (!signature) return false;

  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HMAC', hash: 'SHA-1' },
    false,
    ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, encoder.encode(rawBody));
  const computed = Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');

  // Constant-time comparison
  if (computed.length !== signature.length) return false;
  let mismatch = 0;
  for (let i = 0; i < computed.length; i++) {
    mismatch |= computed.charCodeAt(i) ^ signature.charCodeAt(i);
  }
  return mismatch === 0;
}

function cleanupExpiredEntries(): void {
  const now = Date.now();
  for (const [id, timestamp] of recentDeployments) {
    if (now - timestamp > 60 * 1000) {
      recentDeployments.delete(id);
    }
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Only accept POST requests
    if (request.method !== 'POST') {
      return new Response('Method not allowed', { status: 405 });
    }

    const rawBody = await request.text();
    const signature = request.headers.get('x-vercel-signature');

    // Verify HMAC-SHA1 signature
    const valid = await verifySignature(rawBody, signature, env.VERCEL_WEBHOOK_SECRET);
    if (!valid) {
      return new Response('Invalid signature', { status: 403 });
    }

    // Parse and filter event
    const event = JSON.parse(rawBody);
    if (event.type !== 'deployment.succeeded') {
      return Response.json({ skipped: true, reason: 'not deployment.succeeded' });
    }

    // Deduplication check
    const deploymentId = event.payload?.deployment?.id;
    if (deploymentId) {
      cleanupExpiredEntries();
      if (recentDeployments.has(deploymentId)) {
        return Response.json({ skipped: true, reason: 'duplicate within 60s' });
      }
      recentDeployments.set(deploymentId, Date.now());
    }

    // Trigger rebuild via GitHub repository_dispatch
    const ghResponse = await fetch(
      \\\`https://api.github.com/repos/\\\${env.GITHUB_REPO}/dispatches\\\`,
      {
        method: 'POST',
        headers: {
          Authorization: \\\`Bearer \\\${env.GITHUB_TOKEN}\\\`,
          Accept: 'application/vnd.github+json',
          'Content-Type': 'application/json',
          'User-Agent': 'v2cf-sync-worker',
          'X-GitHub-Api-Version': '2022-11-28',
        },
        body: JSON.stringify({
          event_type: 'v2cf-sync',
          client_payload: {
            vercelDeploymentId: deploymentId,
            timestamp: new Date().toISOString(),
          },
        }),
      }
    );

    if (!ghResponse.ok) {
      const errText = await ghResponse.text();
      return Response.json(
        { error: 'Failed to trigger rebuild', detail: errText },
        { status: 502 }
      );
    }

    return Response.json({
      synced: true,
      vercelDeploymentId: deploymentId,
      timestamp: new Date().toISOString(),
    });
  },
};
`;
}
