import { describe, it, expect } from 'vitest';
import { generateWranglerConfig } from '../../src/orchestrator/config-gen/wrangler-config.js';

describe('generateWranglerConfig', () => {
  const baseConfig = {
    workerName: 'test-worker',
    d1DatabaseName: 'test-db',
    d1DatabaseId: 'uuid-123-abc',
    compatibilityDate: '2025-09-23',
  };

  it('returns valid JSONC with $schema', () => {
    const result = generateWranglerConfig(baseConfig);
    const parsed = JSON.parse(result.replace(/^\/\/.*\n/, ''));
    expect(parsed.$schema).toBe('node_modules/wrangler/config-schema.json');
  });

  it('sets main to .open-next/worker.js', () => {
    const result = generateWranglerConfig(baseConfig);
    const parsed = JSON.parse(result.replace(/^\/\/.*\n/, ''));
    expect(parsed.main).toBe('.open-next/worker.js');
  });

  it('sets name to workerName', () => {
    const result = generateWranglerConfig(baseConfig);
    const parsed = JSON.parse(result.replace(/^\/\/.*\n/, ''));
    expect(parsed.name).toBe('test-worker');
  });

  it('sets compatibility_date from config', () => {
    const result = generateWranglerConfig(baseConfig);
    const parsed = JSON.parse(result.replace(/^\/\/.*\n/, ''));
    expect(parsed.compatibility_date).toBe('2025-09-23');
  });

  it('includes nodejs_compat in compatibility_flags', () => {
    const result = generateWranglerConfig(baseConfig);
    const parsed = JSON.parse(result.replace(/^\/\/.*\n/, ''));
    expect(parsed.compatibility_flags).toContain('nodejs_compat');
  });

  it('configures assets directory and binding', () => {
    const result = generateWranglerConfig(baseConfig);
    const parsed = JSON.parse(result.replace(/^\/\/.*\n/, ''));
    expect(parsed.assets.directory).toBe('.open-next/assets');
    expect(parsed.assets.binding).toBe('ASSETS');
  });

  it('d1_databases[0] has binding DB, matching database_name and database_id', () => {
    const result = generateWranglerConfig(baseConfig);
    const parsed = JSON.parse(result.replace(/^\/\/.*\n/, ''));
    expect(parsed.d1_databases).toHaveLength(1);
    expect(parsed.d1_databases[0].binding).toBe('DB');
    expect(parsed.d1_databases[0].database_name).toBe('test-db');
    expect(parsed.d1_databases[0].database_id).toBe('uuid-123-abc');
  });

  it('services array contains WORKER_SELF_REFERENCE binding', () => {
    const result = generateWranglerConfig(baseConfig);
    const parsed = JSON.parse(result.replace(/^\/\/.*\n/, ''));
    expect(parsed.services).toHaveLength(1);
    expect(parsed.services[0].binding).toBe('WORKER_SELF_REFERENCE');
    expect(parsed.services[0].service).toBe('test-worker');
  });

  it('starts with a generated-by comment', () => {
    const result = generateWranglerConfig(baseConfig);
    expect(result).toMatch(/^\/\/ Generated by v2cf/);
  });
});
