import { SyntaxKind } from 'ts-morph';
import type { SourceFile } from 'ts-morph';
import type { DetectedPattern } from '../../schemas/project-model.js';
import type {
  TransformRule,
  TransformResult,
  TransformContext,
  ChangeDescription,
} from '../types.js';

const IMAGE_LOADER_TEMPLATE = `import type { ImageLoaderProps } from "next/image";

const normalizeSrc = (src: string) => {
  return src.startsWith("/") ? src.slice(1) : src;
};

/**
 * Cloudflare Images loader for next/image.
 * Generated by v2cf.
 */
export default function cloudflareLoader({ src, width, quality }: ImageLoaderProps) {
  const params = [\`width=\${width}\`];
  if (quality) {
    params.push(\`quality=\${quality}\`);
  }
  if (process.env.NODE_ENV === "development") {
    return \`\${src}?\${params.join("&")}\`;
  }
  return \`/cdn-cgi/image/\${params.join(",")}/\${normalizeSrc(src)}\`;
}
`;

/**
 * XFRM-04: Image Loader Generator
 *
 * This transform is special: it is triggered explicitly by the command handler
 * when next/image is detected, not by a specific DetectedPattern match in the
 * pipeline. It generates a Cloudflare Images loader file and updates next.config
 * to reference it.
 *
 * Exported as both a TransformRule (for registry consistency) and a standalone
 * function (for direct invocation from command handlers).
 */

/**
 * Standalone function to generate the image loader.
 * Called directly from command handlers when next/image usage is detected.
 */
export function generateImageLoader(context: TransformContext): TransformResult {
  const changes: ChangeDescription[] = [];
  const warnings: string[] = [];
  const filesGenerated: string[] = [];
  const filesModified: string[] = [];

  const loaderPath = `${context.projectDir}/image-loader.ts`;

  // Idempotency: check if image-loader.ts already exists in the project
  const existingLoader = context.project.getSourceFile(loaderPath);
  if (existingLoader) {
    return {
      ruleId: 'image-loader-gen',
      applied: false,
      filesModified: [],
      filesGenerated: [],
      changes: [],
      warnings: [],
    };
  }

  if (!context.dryRun) {
    // Create the image-loader.ts file in the ts-morph project
    context.project.createSourceFile(loaderPath, IMAGE_LOADER_TEMPLATE);

    // Update next.config to reference the loader
    updateNextConfig(context, filesModified, changes);
  }

  filesGenerated.push('image-loader.ts');

  changes.push({
    file: loaderPath,
    line: 1,
    description: 'Generated Cloudflare Images loader (image-loader.ts)',
    confidence: 'AUTO',
  });

  return {
    ruleId: 'image-loader-gen',
    applied: true,
    filesModified,
    filesGenerated,
    changes,
    warnings,
  };
}

/**
 * Find and update next.config to add images.loader and images.loaderFile.
 * Supports: next.config.ts, next.config.js, next.config.mjs
 * Patterns: `const x = {}; export default x`, `export default { ... }`
 */
function updateNextConfig(
  context: TransformContext,
  filesModified: string[],
  changes: ChangeDescription[]
): void {
  // Try to find next.config in the project
  const configExtensions = ['.ts', '.js', '.mjs'];
  let configFile: SourceFile | undefined;

  for (const ext of configExtensions) {
    const configPath = `${context.projectDir}/next.config${ext}`;
    configFile = context.project.getSourceFile(configPath);
    if (configFile) break;
  }

  if (!configFile) {
    return;
  }

  const filePath = configFile.getFilePath();

  // Check if images config already exists (idempotency)
  const fullText = configFile.getFullText();
  if (fullText.includes('loaderFile')) {
    return;
  }

  // Strategy 1: Find `export default { ... }` (direct object literal export)
  const exportAssignments = configFile.getDescendantsOfKind(
    SyntaxKind.ExportAssignment
  );

  for (const exportAssign of exportAssignments) {
    const expr = exportAssign.getExpression();

    // Direct object literal: export default { ... }
    if (expr.getKind() === SyntaxKind.ObjectLiteralExpression) {
      const objLit = expr.asKindOrThrow(SyntaxKind.ObjectLiteralExpression);
      objLit.addPropertyAssignment({
        name: 'images',
        initializer: `{ loader: 'custom', loaderFile: './image-loader.ts' }`,
      });
      filesModified.push(filePath);
      changes.push({
        file: filePath,
        line: 1,
        description: 'Added images.loader and images.loaderFile to next.config',
        confidence: 'AUTO',
      });
      return;
    }

    // Variable reference: export default nextConfig
    if (expr.getKind() === SyntaxKind.Identifier) {
      const varName = expr.getText();
      // Find the variable declaration for this identifier
      const varDecls = configFile.getDescendantsOfKind(
        SyntaxKind.VariableDeclaration
      );
      for (const varDecl of varDecls) {
        if (varDecl.getName() === varName) {
          const init = varDecl.getInitializer();
          if (init && init.getKind() === SyntaxKind.ObjectLiteralExpression) {
            const objLit = init.asKindOrThrow(SyntaxKind.ObjectLiteralExpression);
            objLit.addPropertyAssignment({
              name: 'images',
              initializer: `{ loader: 'custom', loaderFile: './image-loader.ts' }`,
            });
            filesModified.push(filePath);
            changes.push({
              file: filePath,
              line: 1,
              description:
                'Added images.loader and images.loaderFile to next.config',
              confidence: 'AUTO',
            });
            return;
          }
        }
      }
    }
  }

  // If we couldn't find a pattern to modify, insert a comment
  configFile.insertText(
    0,
    '// v2cf: Add `images: { loader: "custom", loaderFile: "./image-loader.ts" }` to your Next.js config.\n'
  );
  filesModified.push(filePath);
  changes.push({
    file: filePath,
    line: 1,
    description:
      'Inserted manual instruction comment for next.config image loader setup',
    confidence: 'REVIEW',
  });
}

/**
 * TransformRule implementation for registry consistency.
 * In practice, image-loader-gen is called directly via generateImageLoader(),
 * not through the pattern-matching pipeline, since it doesn't match a specific
 * DetectedPattern type.
 */
export const imageLoaderGen: TransformRule = {
  id: 'image-loader-gen',
  name: 'Image Loader Generator',
  description:
    'Generates a Cloudflare Images loader file (image-loader.ts) and updates next.config',
  appliesTo: [], // Not triggered by pattern matching -- called directly
  dependencies: [],

  transform(
    _sourceFile: SourceFile,
    _pattern: DetectedPattern,
    context: TransformContext
  ): TransformResult {
    return generateImageLoader(context);
  },
};
