interface WranglerConfigInput {
  workerName: string;
  d1DatabaseName: string;
  d1DatabaseId: string;
  compatibilityDate: string;
}

export function generateWranglerConfig(config: WranglerConfigInput): string {
  const wranglerObj = {
    $schema: 'node_modules/wrangler/config-schema.json',
    main: '.open-next/worker.js',
    name: config.workerName,
    compatibility_date: config.compatibilityDate,
    compatibility_flags: ['nodejs_compat'],
    assets: {
      directory: '.open-next/assets',
      binding: 'ASSETS',
    },
    services: [
      {
        binding: 'WORKER_SELF_REFERENCE',
        service: config.workerName,
      },
    ],
    d1_databases: [
      {
        binding: 'DB',
        database_name: config.d1DatabaseName,
        database_id: config.d1DatabaseId,
      },
    ],
  };

  return `// Generated by v2cf - do not edit manually\n${JSON.stringify(wranglerObj, null, 2)}\n`;
}
