/**
 * XFRM-05: D1 Schema Generator
 *
 * Generates SQL migration files from detected KV operation arrays.
 * The migration creates the D1 tables needed by the adapter template.
 *
 * Always generates kv_store (key-value). Conditionally generates kv_list
 * when list operations (lpush, lrange, rpush, llen) are detected.
 */

const LIST_OPS = ['lpush', 'lrange', 'rpush', 'llen'];

/**
 * Generate a complete SQL migration file from a list of detected KV operations.
 *
 * @param operations - Array of KV operation names detected in the source (e.g., ['get', 'set', 'lpush'])
 * @returns Complete .sql file content string with header comment
 */
export function generateMigrationSQL(operations: string[]): string {
  const needsList = operations.some((op) => LIST_OPS.includes(op));

  const lines: string[] = [];

  // Header comment
  lines.push('-- Migration: 0001_kv_schema.sql');
  lines.push('-- Generated by v2cf from @vercel/kv usage analysis');
  lines.push('');

  // kv_store table (always generated)
  lines.push('-- Key-value store (get/set/del/incr/expire)');
  lines.push('CREATE TABLE IF NOT EXISTS kv_store (');
  lines.push('  key TEXT PRIMARY KEY,');
  lines.push('  value TEXT NOT NULL,');
  lines.push('  expires_at REAL  -- Unix timestamp, NULL = no expiry');
  lines.push(');');
  lines.push('');

  // kv_list table (conditional)
  if (needsList) {
    lines.push('-- List store (lpush/lrange)');
    lines.push('CREATE TABLE IF NOT EXISTS kv_list (');
    lines.push('  id INTEGER PRIMARY KEY AUTOINCREMENT,');
    lines.push('  key TEXT NOT NULL,');
    lines.push('  value TEXT NOT NULL,');
    lines.push('  position INTEGER NOT NULL,');
    lines.push("  created_at REAL NOT NULL DEFAULT (unixepoch('now', 'subsec'))");
    lines.push(');');
    lines.push('');
    lines.push(
      'CREATE INDEX IF NOT EXISTS idx_kv_list_key_position ON kv_list (key, position DESC);'
    );
  }

  // Indexes
  lines.push(
    'CREATE INDEX IF NOT EXISTS idx_kv_store_expires ON kv_store (expires_at) WHERE expires_at IS NOT NULL;'
  );
  lines.push('');

  return lines.join('\n');
}
